spring:
  application:
    name: bancs-db-service
---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888/
---
spring:
  config:
    activate:
      on-profile: localHostApp
    import: optional:configserver:${CONFIG_SERVER_URL:http://host.docker.internal:8888/}
